# Generated by Django 4.0.2 on 2022-02-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instrument_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='posted_by',
        ),
    ]
