# Generated by Django 4.0.2 on 2022-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
