# Generated by Django 4.0.2 on 2022-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/blog/image/'),
        ),
    ]
