# Generated by Django 4.0.2 on 2022-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fileupload',
        ),
        migrations.AddField(
            model_name='review',
            name='file_upload',
            field=models.ImageField(default='default.jpg', upload_to='uploads/review/image/'),
        ),
    ]
