# Generated by Django 4.0.2 on 2022-04-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='file_upload',
        ),
    ]
