# Generated by Django 2.2.27 on 2022-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image_url',
            field=models.FileField(null=True, upload_to='uploads/instrument/image/'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='object_3d',
            field=models.FileField(null=True, upload_to='uploads/instrument/obj/'),
        ),
    ]
