# Generated by Django 4.0.2 on 2022-03-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_order_id'),
        ('shop', '0002_remove_order_item_order_count_order_instrument'),
    ]

    operations = [
    ]
