# Generated by Django 4.0.2 on 2022-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_review_text_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='ad_info',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
