# Generated by Django 4.0.2 on 2022-03-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_subtotal_alter_order_city_alter_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
