# Generated by Django 2.2.27 on 2022-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220226_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='object_mtl',
            field=models.FileField(null=True, upload_to='uploads/instrument/mtl/'),
        ),
    ]
