# Generated by Django 4.0.2 on 2022-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_delivery_confirmed_order_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_confirmed',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shopper_confirmed',
            new_name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
