# Generated by Django 4.0.2 on 2022-03-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
