# Generated by Django 4.0.2 on 2022-04-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/instrument/image/'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/instrument/image/'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image3',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/instrument/image/'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image4',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/instrument/image/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
