# Generated by Django 4.0.2 on 2022-03-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='count',
            new_name='quantity',
        ),
    ]
