# Generated by Django 4.0.2 on 2022-04-15 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_rename_delivery_confirmed_order_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='zip_Code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='telephone',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='UncompletedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20, null=True)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('apartment', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=200)),
                ('zip_Code', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
