# Generated by Django 4.0.2 on 2022-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_full_address_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncompletedorder',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
