# Generated by Django 2.2.27 on 2022-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220226_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='object_3d',
            field=models.FileField(blank=True, null=True, upload_to='uploads/instrument/obj/'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='object_mtl',
            field=models.FileField(blank=True, null=True, upload_to='uploads/instrument/mtl/'),
        ),
    ]
