# Generated by Django 4.0.2 on 2022-04-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitem_quantity_uncompletedorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uncompletedorderitem',
            old_name='order',
            new_name='uncompleted_order',
        ),
    ]
