# Generated by Django 4.0.2 on 2022-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_order_uncompletedorderitem_uncompleted_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
