# Generated by Django 2.2.27 on 2022-02-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220227_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='order_id',
            new_name='order',
        ),
    ]
