# Generated by Django 4.0.2 on 2022-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ad_info',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ex_detail',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/instrument/image/'),
        ),
    ]
