# Generated by Django 4.0.2 on 2022-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_priority_alter_instrument_ad_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='ad_info_de_DE',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_en',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_es_ES',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_fr_FR',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_ja_JP',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_ru_RU',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_uk_UA',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ad_info_zh_CN',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_de_DE',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_en',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_es_ES',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_fr_FR',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_ja_JP',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_ru_RU',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_uk_UA',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='details_zh_CN',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_de_DE',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_en',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_es_ES',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_fr_FR',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_ja_JP',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_ru_RU',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_uk_UA',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ex_detail_zh_CN',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_de_DE',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_es_ES',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_fr_FR',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_ja_JP',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_ru_RU',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_uk_UA',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name_zh_CN',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
