# Generated by Django 4.0.2 on 2022-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220227_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='details',
            field=models.TextField(max_length=3000),
        ),
    ]
