# Generated by Django 4.0.2 on 2022-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_instrument_old_price_alter_instrument_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
