# Generated by Django 4.0.2 on 2022-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_instrument_old_price_alter_instrument_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='details',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
