# Generated by Django 4.0.2 on 2022-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_instrument_extras_instrument_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='object_gltf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/instrument/gltf/'),
        ),
    ]
