# Generated by Django 4.0.2 on 2022-05-21 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_instrument_object_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='quantity',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
