# Generated by Django 4.0.2 on 2022-05-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_instrument_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncompletedOrderModelItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('customModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.custommodel')),
                ('uncompleted_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_items', to='shop.uncompletedorder')),
            ],
        ),
    ]
