# Generated by Django 4.0.2 on 2022-04-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0011_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.instrument')),
            ],
        ),
    ]
